services:
  api_py:
    build: ./pyapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SCHEMA: ml
    depends_on: [db]
    expose: ["8000"]
  worker:
    image: prefecthq/prefect:2-latest   # o apache/airflow si prefereixes
    restart: unless-stopped
    env_file: .env
    depends_on: [db]
    volumes:
      - ./flows:/opt/flows
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    restart: unless-stopped
    command: mlflow server --host 0.0.0.0 --port 5000 \
      --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlartifacts
    volumes:
      - ./mlruns:/mlartifacts
    expose: ["5000"]
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/000-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db
    expose:
      - "3000"
  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frontend:/srv:ro
    ports:
      - "80:80"
volumes:
  pgdata:
